sudo: false

language: ruby
rvm:
  - 2.2.1

bundler_args: --deployment --without development doc production --jobs=3 --retry=3
cache: bundler

addons:
  postgresql: 9.3

before_script:
  - export DATABASE_USERNAME=postgres
  - bundle exec rake db:setup

script: bundle exec rake spec
