sudo: false
language: ruby
bundler_args: --deployment --without development doc production --jobs=3 --retry=3
cache: bundler
rvm:
  - 2.2.0

addons:
  postgresql: 9.3

before_script:
  - export DATABASE_USERNAME=postgres
  - bundle exec rake db:setup

script: bundle exec rake spec
